In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_df = pd.read_csv('data/pakistan-media-dataset-synthetic.csv')

In [3]:
df = raw_df.copy()

# Clean Data

In [4]:
df[["Region", "City"]]

Region        City
0      Islamabad      Multan
1          Sindh      Quetta
2          Sindh  Rawalpindi
3      Islamabad      Multan
4          Sindh     Karachi
...          ...         ...
14995        KPK     Karachi
14996     Punjab      Quetta
14997  Islamabad    Peshawar
14998      Sindh      Multan
14999        KPK     Karachi

[15000 rows x 2 columns]

## Region-City Cleaning
We can clearly see wrong regions associated with cities. Let's fix that

In [5]:
# Let's print the unique cities
df["City"].unique()

array(['Multan', 'Quetta', 'Rawalpindi', 'Karachi', 'Peshawar',
       'Islamabad', 'Lahore', 'Hyderabad'], dtype=object)

In [6]:
# Let's print the unique regions
df["Region"].unique()

array(['Islamabad', 'Sindh', 'Balochistan', 'KPK', 'Punjab', 'AJK'],
      dtype=object)

In [7]:
def get_region(city):
    if city in ["Multan", "Rawalpindi", "Lahore"]: return "Punjab"
    elif city in ["Quetta"]: return "Balochistan"
    elif city in ["Karachi", "Hyderabad"]: return "Sindh"
    elif city in ["Peshawar"]: return "KPK"
    elif city in ["Islamabad"]: return "Islamabad"
    else: return pd.NA

df["Region"] = df["City"].apply(get_region)


In [8]:
df[["Region", "City"]]

Region        City
0           Punjab      Multan
1      Balochistan      Quetta
2           Punjab  Rawalpindi
3           Punjab      Multan
4            Sindh     Karachi
...            ...         ...
14995        Sindh     Karachi
14996  Balochistan      Quetta
14997          KPK    Peshawar
14998       Punjab      Multan
14999        Sindh     Karachi

[15000 rows x 2 columns]

## Language Field Cleaning

In [9]:
df["Language"].unique()

array(['English', 'urdu', 'Urdu', 'ENG', nan], dtype=object)

In [10]:
lang_replacement_dict = { "English": "en", "urdu": "ur", "Urdu": "ur", "ENG": "en"}
df["Language"] = df["Language"].replace(lang_replacement_dict)

In [11]:
df["Language"].unique()

array(['en', 'ur', nan], dtype=object)

## Advertisement Revenue Cleaning

### Fix Different Monetary Values

In [12]:
def get_clean_revenue(d):
    f = None

    try:
        f = float(d)
        return f
    except:
        pass

    value, value_multiplier = d.split(" ")

    if value_multiplier == "lakh": return float(value) * 100_000
    elif value_multiplier == "crore": return float(value) * 10_000_000
    elif value_multiplier == "million": return float(value) * 1_000_000
    else: print(value_multiplier)

In [13]:
df["Revenue"] = df["Revenue"].apply(get_clean_revenue)

### Fix negative revenue

In [14]:
df["Revenue"] = pd.to_numeric(df['Revenue'], errors="coerce").clip(lower=0)

## Journalist Cleaning

In [15]:
df["Journalist"].unique()


array(['Najam Sethi', 'Dr. Shahid Masood', 'Kamran Shahid',
       'Matiullah Jan', 'RAUF KLASSRA', 'Ansar Abbasi', 'Umar Cheema',
       'Shahzeb Khanzada', 'shahzeb khanzada', 'Kamran Khan', 'K. Khan',
       'Asma Shirazi', 'Mohsin Raza Khan', 'Saleem Safi', 'Talat Hussain',
       'Rauf Klasra', 'Owais Tohid', 'Nusrat Javed', 'Mohsin Raza'],
      dtype=object)

In [16]:
journalist_replacement_dict = { "RAUF KLASSRA": "Rauf Klasra", "Mohsin Raza Khan": "Mohsin Raza", "K. Khan": "Kamran Khan", "shahzeb khanzada": "Shahzeb Khanzada" }
df["Journalist"] = df["Journalist"].replace(journalist_replacement_dict)

In [17]:
df["Journalist"].unique()

array(['Najam Sethi', 'Dr. Shahid Masood', 'Kamran Shahid',
       'Matiullah Jan', 'Rauf Klasra', 'Ansar Abbasi', 'Umar Cheema',
       'Shahzeb Khanzada', 'Kamran Khan', 'Asma Shirazi', 'Mohsin Raza',
       'Saleem Safi', 'Talat Hussain', 'Owais Tohid', 'Nusrat Javed'],
      dtype=object)

In [18]:
df["Journalist"] = df["Journalist"].str.title()

In [19]:
df["Journalist"].unique()

array(['Najam Sethi', 'Dr. Shahid Masood', 'Kamran Shahid',
       'Matiullah Jan', 'Rauf Klasra', 'Ansar Abbasi', 'Umar Cheema',
       'Shahzeb Khanzada', 'Kamran Khan', 'Asma Shirazi', 'Mohsin Raza',
       'Saleem Safi', 'Talat Hussain', 'Owais Tohid', 'Nusrat Javed'],
      dtype=object)

## Channel Cleaning

In [20]:
df["Channel"].unique()

array(['ARY News', 'HUM News', 'Samaa', 'DawnNews', 'SAMAA TV', 'geo',
       'AbbTakk News', 'hum news', 'Geo', 'Express-News', 'GEO NEWS',
       'ARYNEWS', 'ary', 'DAWN', 'Express', 'ARY'], dtype=object)

In [21]:
channel_replacement_dict = {"ARYNEWS": "ARY News", "Samaa": "SAMAA TV", "DawnNews": "DAWN", "geo": "Geo News", "AbbTakk News": "Abb Takk News", "hum news": "HUM News", "Geo": "Geo News", "Express-News": "Express News", "GEO NEWS": "Geo News", "ARYNEWS": "ARY News", "ary": "ARY News", "Express": "Express News", "ARY": "ARY News"}
df["Channel"] = df["Channel"].replace(channel_replacement_dict)

In [22]:
df["Channel"].unique()

array(['ARY News', 'HUM News', 'SAMAA TV', 'DAWN', 'Geo News',
       'Abb Takk News', 'Express News'], dtype=object)

## Topic & Headline Cleaning

In [23]:
df["Topic"].unique()

array(['Sports', 'Crime', 'Health', 'Terrorism', 'Media', 'Education',
       'Judiciary', 'Politics', 'Economy'], dtype=object)

In [24]:
df["Headline"].unique()

array(['Polio cases reported in KPK',
       'Budget deficit reaches record high',
       'Attack on Army convoy in Waziristan',
       'Hospitals face medicine shortages',
       'Chief Justice orders suo moto on Karachi violence',
       'Karachi Kings beat Multan Sultans',
       'Doctors protest low salaries',
       'Health workers go on strike in Punjab',
       'Stock exchange crashes amid crisis',
       'Militant hideout destroyed in KPK',
       'Opposition stages walkout in National Assembly',
       'Dawn faces backlash over editorial',
       'Remittances fall sharply in July',
       'Judiciary under pressure, say analysts',
       'Suicide bombing in Peshawar mosque',
       'Cricket team departs for World Cup',
       'Pakistan football team defeats India',
       'Security forces foil major terror bid',
       'High Court stays government decision',
       'NDMA warns of heavy rains in Punjab',
       'Women cricket team sets new record',
       'Exports see slight rec

In [25]:
def get_topic(headline):
    headline = headline.lower()

    topics = {
        'Sports': ['cricket', 'football', 'hockey', 'psl', 'match', 'beat', 'defeats', 'team', 'world cup', 'tournament', 'sports', 'babar azam'],
        'Crime': ['attack', 'kill', 'murder', 'suicide', 'bomb', 'blast', 'arrest', 'raid', 'suspect', 'kidnap', 'theft', 'shooting'],
        'Health': ['hospital', 'doctor', 'medicine', 'health', 'dengue', 'polio', 'covid', 'vaccination', 'virus', 'disease', 'shortage', 'mental'],
        'Terrorism': ['terror', 'militant', 'ttp', 'bombing', 'waziristan', 'convoy', 'ispr', 'operation', 'blast'],
        'Media': ['pemra', 'journalist', 'anchor', 'channel', 'media', 'editorial', 'news', 'censorship', 'talkshow', 'report'],
        'Education': ['university', 'school', 'teacher', 'student', 'education', 'curriculum', 'exam', 'scholarship', 'hec'],
        'Judiciary': ['court', 'judge', 'justice', 'cj', 'supreme court', 'high court', 'case', 'suo moto', 'lawyer', 'bar association'],
        'Politics': ['pm', 'assembly', 'minister', 'senate', 'government', 'cabinet', 'opposition', 'election', 'party', 'politics', 'rally', 'pmln', 'ppp', 'khan'],
        'Economy': ['budget', 'deficit', 'economy', 'imf', 'trade', 'stock', 'dollar', 'revenue', 'investment', 'exports', 'imports', 'tax', 'price', 'funds', 'remittance']
    }

    for topic, keywords in topics.items():
        if any(word in headline for word in keywords):
            return topic

    return 'Other'

In [26]:
df["Topic"] = df["Headline"].apply(get_topic)

## Ratings Cleaning

In [27]:
df["Ratings"] = df["Ratings"].clip(upper=100)

## Airtime Cleaning

In [28]:
df["Airtime"][df["Airtime"] < 0]

50      -22.0
108      -5.0
127     -17.0
197     -26.0
218     -18.0
         ... 
14920    -4.0
14929   -20.0
14941   -28.0
14944    -8.0
14976   -15.0
Name: Airtime, Length: 433, dtype: float64

In [29]:
df["Airtime"] = df["Airtime"].clip(lower=0)

In [30]:
df["Airtime"][df["Airtime"] < 0]

Series([], Name: Airtime, dtype: float64)

In [31]:
df["Airtime"][df["Airtime"] >= 0]

0         25.0
2        223.0
4        223.0
7        117.0
9        201.0
         ...  
14992    418.0
14993    157.0
14994    134.0
14998    150.0
14999    324.0
Name: Airtime, Length: 7489, dtype: float64

## Bias Score Cleaning

In [32]:
df["BiasScore"].unique()

array([nan,  5.,  2., -1.,  4.,  1.,  3.,  0.])

In [33]:
df["BiasScore"] = df["BiasScore"].clip(lower=0, upper=10)

In [34]:
df["BiasScore"].unique()

array([nan,  5.,  2.,  0.,  4.,  1.,  3.])

## Viewership Cleaning

In [35]:
df["Viewership"].agg(["min","max"])

min    1.047036e-01
max    1.999177e+06
Name: Viewership, dtype: float64

In [36]:
def get_cleaned_viewership(f):
    if np.isnan(f): return f

    return int(f)

df["Viewership"] = df["Viewership"].apply(get_cleaned_viewership)

In [37]:
df["Viewership"].agg(["min","max"])

min          0.0
max    1999177.0
Name: Viewership, dtype: float64

## Shares Cleaning

In [38]:
df["Shares"].agg(["min","max"])

min       127.0
max    199998.0
Name: Shares, dtype: float64

In [39]:
def get_cleaned_shares(f):
    if np.isnan(f): return f

    return int(f)

df["Shares"] = df["Shares"].apply(get_cleaned_shares)

In [40]:
df["Shares"].agg(["min","max"])

min       127.0
max    199998.0
Name: Shares, dtype: float64

Technically there seems to be nothing to clean in this column

## Adspend Cleaning

In [41]:
df["AdSpend"].unique()

array(['4452987.876', '1 crore', '50 lakh', ..., '3539926.21',
       '1291429.491', '3355467.497'], shape=(3746,), dtype=object)

In [42]:
df["AdSpend"] = df["AdSpend"].apply(get_clean_revenue)

In [43]:
df["AdSpend"].unique()

array([ 4452987.876, 10000000.   ,  5000000.   , ...,  3539926.21 ,
        1291429.491,  3355467.497], shape=(3746,))

## Controversy Flag

In [44]:
df["ControversyFlag"].unique()

array(['No', '1', 'Yes', nan, '0'], dtype=object)

In [45]:
controversy_flag_replacement_dict = { "No": False, "1": True, "Yes": True, "0": False }

df["ControversyFlag"] = df["ControversyFlag"].replace(controversy_flag_replacement_dict)

In [47]:
df["ControversyFlag"].unique()

array([False, True, nan], dtype=object)

## SocialMediaInteractions Cleaning

In [63]:
df["SocialMediaInteractions"].agg(["min", "max", "std", "mean"])

min       103.000000
max     49984.000000
std     14361.148557
mean    25044.750806
Name: SocialMediaInteractions, dtype: float64

In [64]:
def get_cleaned_social_media_interactions(f):
    if np.isnan(f): return f

    return int(f)

df["SocialMediaInteractions"] = df["SocialMediaInteractions"].apply(get_cleaned_social_media_interactions)

In [65]:
df["SocialMediaInteractions"].agg(["min", "max", "std", "mean"])

min       103.000000
max     49984.000000
std     14361.148557
mean    25044.750806
Name: SocialMediaInteractions, dtype: float64